[package]
name = "std"
version = "0.1.0"
authors = ["Folyd <lyshuhow@gmail.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
select = "0.5.0"