[package]
name = "posix"
version = "0.1.0"
authors = ["Folyd <lyshuhow@gmail.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
select = "0.5.0"
serde_json = "1.0.61"
